function x = Rrph_f(roll,pitch,heading)
Rroll_f = @(roll)(...
    [   cosd(roll)	0	sind(roll);     ...
        0           1	0;              ...
        -sind(roll)	0	cosd(roll)]     ...
    );
    
Rpitch_f = @(pitch)(...
    [   1 0             0;              ...
        0 cosd(pitch)   -sind(pitch);	...
        0 sind(pitch)   cosd(pitch)]    ...
    );
    
Rheading_f = @(heading)(...
    [   cosd(heading)	sind(heading)   0;	...
        -sind(heading)	cosd(heading)   0;	...
        0               0               1]	...
    );

x = (Rheading_f(heading)*Rpitch_f(pitch)*Rroll_f(roll));
