function x = Rrph_f2(roll,pitch,heading)
 heading= -heading;
 pitch = -pitch;
Wh = [ ... heading rotation matrix
     cosd(heading), sind(heading), 0; ...
    -sind(heading), cosd(heading), 0; ...
     0,            0,            1; ...
    ];

Wp = [ ... pitch rotation matrix
    cosd(pitch),  0, -sind(pitch); ...
             0,  1,  0;          ...
    sind(pitch),  0,  cosd(pitch); ...
    ];

Wr = [ ... roll rotation matrix
    1,  0,         0;         ...
    0,  cosd(roll), sind(roll); ...
    0, -sind(roll), cosd(roll); ...
    ];
dcm_earth2body = Wr * Wp * Wh;

x = dcm_earth2body';